language: python
python:
  - '2.7'

install:
    pip install -r TestGround/test/requirements.txt

before_script:
  - wget https://github.com/nu-radio/radiotools/archive/master.zip -O /tmp/radiotools.zip
  - unzip /tmp/radiotools.zip
  - mv radiotools-master radiotools
  - ls $PWD
  - echo $PWD
  - echo $PYTHONPATH
  - export PYTHONPATH=$PWD/radiotools
  - echo $PYTHONPATH

script:
    - TestGround/test/test.py