language: python
python:
  - '2.7'

install:
    pip install -r TestGround/test/requirements.txt

addons:
  apt:
    packages:
        - hdf5
        - gsl

before_script:
  - wget https://github.com/nu-radio/radiotools/archive/master.zip -O /tmp/radiotools.zip
  - unzip /tmp/radiotools.zip
  - mv radiotools-master radiotools
  - export PYTHONPATH=$PWD/radiotools
  - wget https://github.com/nu-radio/NuRadioReco/archive/master.zip -O /tmp/NuRadioReco.zip
  - unzip /tmp/NuRadioReco.zip
  - mv NuRadioReco-master NuRadioReco
  - export PYTHONPATH=$PYTHONPATH:$PWD/NuRadioReco

script:
    - TestGround/test/test.py