language: python
python:
  - '2.7'

install:
    pip install -r TestGround/test/requirements.txt

before_script:
  - wget https://github.com/nu-radio/radiotools/archive/master.zip -O /tmp/radiotools.zip
  - unzip /tmp/radiotools.zip
  - export PYTHONPATH=$PYTHONPATH:$PWD/radiotools

script:
    - TestGround/test/test.py
    - TestGround/test/validate.sh